language: php
php:
  - 7.0
  - 5.6
  - 5.5
install:
  - rm -rf ..?* .[!.]* *
  - ls -al
  - curl -s http://getcomposer.org/installer | php
  - composer self-update
  - composer create-project cakephp/app .
  - composer require makallio85/yaml-route
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_success:
  - travis_retry php vendor/bin/coveralls