language: php
php:
  - 5.6
install:
  - rm -rf ..?* .[!.]* *
  - cd ..
  - curl -s http://getcomposer.org/installer | php
  - composer self-update
  - composer create-project cakephp/app app
  - cd app
  - composer require phpunit/phpunit
  - composer require satooshi/php-coveralls
  - composer require makallio85/yaml-route "dev-master"
  - cp vendor/makallio85/yaml-route/tests/config/routes.yml config/routes.yml
  - cp -Rf vendor/makallio85/yaml-route/tests/plugins/* plugins/*
  - cd plugins
  - ls -al
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c vendor/makallio85/yaml-route/phpunit.xml.dist
after_success:
  - travis_retry php vendor/bin/coveralls